<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="redm" nsURI="http://spi-fm.uca.es/spdef/models/specificTools/redm/1.0"
    nsPrefix="redm">
  <eClassifiers xsi:type="ecore:EClass" name="RedmineDatabase">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wikiDatabase" eType="ecore:EClass ../../genericTools/wikim/WikitoolModel.ecore#//WikiDatabase"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="apiAccessKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="issueTrackingDatabase"
        eType="ecore:EClass ../../genericTools/itm/IssueTrackingtoolModel.ecore#//IssueTrackingDatabase"/>
  </eClassifiers>
</ecore:EPackage>
