<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="vmm" nsURI="http://spi-fm.uca.es/spdef/models/genericTools/vmm/1.0.ecore"
    nsPrefix="vmm">
  <eClassifiers xsi:type="ecore:EClass" name="ModelRepository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="projects" upperBound="-1"
        eType="#//Project" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagrams" upperBound="-1"
        eType="#//Diagram" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="embeddedPackages" upperBound="-1"
        eType="#//Package" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Element" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Diagram">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//DiagramType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedElements" upperBound="-1"
        eType="#//Element"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ElementType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectors" upperBound="-1"
        eType="#//Connector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connector">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Element"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ConnectorType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="#//Package" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ElementType">
    <eLiterals name="CLASS"/>
    <eLiterals name="USECASE" value="1"/>
    <eLiterals name="COMPONENT" value="2"/>
    <eLiterals name="NODE" value="3"/>
    <eLiterals name="OBJECT" value="4"/>
    <eLiterals name="STATE" value="5"/>
    <eLiterals name="ACTIVITY" value="6"/>
    <eLiterals name="ARTIFACT" value="7"/>
    <eLiterals name="REQUIREMENT" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConnectorType">
    <eLiterals name="ASSOCIATION"/>
    <eLiterals name="AGGREGATION" value="1"/>
    <eLiterals name="COMPOSITION" value="2"/>
    <eLiterals name="DEPENDENCY" value="3"/>
    <eLiterals name="INCLUDE" value="4"/>
    <eLiterals name="EXTEND" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DiagramType">
    <eLiterals name="USECASE"/>
    <eLiterals name="CLASS" value="1"/>
    <eLiterals name="ACTIVITY" value="2"/>
    <eLiterals name="COMPONENT" value="3"/>
    <eLiterals name="DEPLOYMENT" value="4"/>
    <eLiterals name="SEQUENCE" value="5"/>
    <eLiterals name="STATECHART" value="6"/>
    <eLiterals name="COLLABORATION" value="7"/>
    <eLiterals name="OTHER" value="8"/>
  </eClassifiers>
</ecore:EPackage>
