<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="swpm" nsURI="http://spi-fm.uca.es/spdef/models/deployment/swpm/1.0"
    nsPrefix="swpm">
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eStructuralFeatures xsi:type="ecore:EReference" name="workproducts" upperBound="-1"
        eType="#//WorkProduct" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkProduct" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Section">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="order" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="embeddedSections" upperBound="-1"
        eType="#//Section" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="models" upperBound="-1"
        eType="#//Model" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specifications" upperBound="-1"
        eType="#//Specification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ModelType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ModelType">
    <eLiterals name="USECASE" literal="USECASE"/>
    <eLiterals name="CLASS" value="1" literal="CLASS"/>
    <eLiterals name="ACTIVITY" value="2"/>
    <eLiterals name="COMPONENT" value="3"/>
    <eLiterals name="DEPLOYMENT" value="4"/>
    <eLiterals name="SEQUENCE" value="5"/>
    <eLiterals name="STATECHART" value="6"/>
    <eLiterals name="COLLABORATION" value="7"/>
    <eLiterals name="OTHER" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Specification">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="details" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//SpecificationType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeWorkProduct" eSuperTypes="#//InternalProduct">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="#//SourcePackage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentaryWorkProduct" eSuperTypes="#//InternalProduct">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sections" upperBound="-1"
        eType="#//Section" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeliverableProduct" eSuperTypes="#//WorkProduct">
    <eStructuralFeatures xsi:type="ecore:EReference" name="embeddedWorkproducts" upperBound="-1"
        eType="#//WorkProduct"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//DeliverableType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalProduct" eSuperTypes="#//WorkProduct"/>
  <eClassifiers xsi:type="ecore:EEnum" name="DeliverableType">
    <eLiterals name="DOC"/>
    <eLiterals name="SOURCE" value="1"/>
    <eLiterals name="ARCHIVE" value="2"/>
    <eLiterals name="INSTALLER" value="3"/>
    <eLiterals name="PACKAGE" value="4"/>
    <eLiterals name="OTHER" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourcePackage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//Archetype"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Archetype">
    <eLiterals name="J2EE"/>
    <eLiterals name="STRUTS2" value="1"/>
    <eLiterals name="SPRING_OSGI" value="2"/>
    <eLiterals name="JSF" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SpecificationType">
    <eLiterals name="TEXTUAL" value="1"/>
    <eLiterals name="EXTERNALCONTENT" value="2"/>
    <eLiterals name="ITEMLIST" value="3"/>
  </eClassifiers>
</ecore:EPackage>
